spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: LevshaNumberOne1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: d462fb12f03ed6d0a382
            client-secret: 910fc30f47f37433e34aa0bb2240b43d4b3686d9